### ISSUE TITLE
The download link is not working!

### ISSUE THREAD

**Issue by MakkaiSzilard** [chrisjz/sm64vr#35]
The download link is not working. That's why I can't download Super Mario 64 VR.
Here is an image of the error: https://user-images.githubusercontent.com/101936628/162573985-bdcdb5b7-fba6-4f38-a837-7fe35db77b03.png

**Comment by chrisjz** [comment]
Unfortunately, I don't have a copy of that file anymore after searching through all my storage and I don't have access to that server which hosted the original file.

If anyone else still has a copy, please message me and I will find another place to host it.

**Comment by MakkaiSzilard** [comment]
I was able to download Super Mario 64 VR using archive.org. Here is the file: https://1drv.ms/u/s!AvsGdKLj08DFjHPRIXggbtzVFTaG?e=C5pQan

**Comment by chrisjz** [comment]
Thanks @MakkaiSzilard !

Link is now updated with a working version.
